[tasks.default]
clear = true
dependencies = [
    "install",
    "build-cli",
    "codegen",
    "build-ui",
    "test",
    "lint-check",
]

[tasks.install]
dependencies = ["install-ui"]

[tasks.install-ui]
command = "pnpm"
args = ["install"]

[tasks.build-cli]
command = "cargo"
args = ["build"]

[tasks.build-ui]
command = "turbo"
args = ["build"]
dependencies = ["codegen-gql"]

[tasks.build]
dependencies = ["build-cli", "build-ui"]

[tasks.test-cli]
command = "cargo"
args = ["test", "--all-features"]

[tasks.test]
clear = true
dependencies = ["test-cli"]

[tasks.coverage-cli-setup]
script = [
    "rm -rf ${CARGO_MAKE_WORKSPACE_WORKING_DIRECTORY}/target/coverage/raw/*.profraw",
]

# Enable backtrace & coverage for tests
[tasks.coverage-cli-setup.env]
RUST_BACKTRACE = "1"
RUSTFLAGS = '-Cinstrument-coverage --cfg uuid_unstable'
# To prevent the build cache from being smashed by the differences between the
# coverage and non-coverage builds, we need to set a different target directory.
CARGO_TARGET_DIR = '${CARGO_MAKE_WORKSPACE_WORKING_DIRECTORY}/target/coverage'

[tasks.coverage-cli-lcov]
command = "grcov"
args = [
    ".",
    "-s",
    "./crates/",
    "--binary-path",
    "./target/coverage/",
    "-t",
    "lcov",
    "--branch",
    "--ignore-not-existing",
    "--keep-only",
    "**/src/**",
    "--ignore",
    "**/.cargo/**",
    "--ignore",
    "**/target/coverage/**",
    "--ignore",
    "**/target/debug/**",
    "-o",
    "./target/coverage/lcov.info",
]
install_crate = { crate_name = "grcov", binary = "grcov", test_arg = "--version" }

[tasks.coverage-cli-md]
command = "grcov"
args = [
    ".",
    "-s",
    "./crates/",
    "--binary-path",
    "./target/coverage/",
    "-t",
    "markdown",
    "--branch",
    "--ignore-not-existing",
    "--keep-only",
    "**/src/**",
    "--ignore",
    "**/.cargo/**",
    "--ignore",
    "**/target/coverage/**",
    "--ignore",
    "**/target/debug/**",
    "-o",
    "./target/coverage/coverage.md",
]
install_crate = { crate_name = "grcov", binary = "grcov", test_arg = "--version" }

[tasks.coverage-cli-report]
command = "cat"
args = ["./target/coverage/coverage.md"]

[tasks.coverage-cli]
dependencies = [
    "coverage-cli-setup",
    "test-cli",
    "coverage-cli-lcov",
    "coverage-cli-md",
    "coverage-cli-report",
]

[tasks.coverage]
dependencies = ["coverage-cli"]

[tasks.lint-check-cli-fmt]
command = "cargo"
args = ["fmt", "--", "--check"]

[tasks.lint-check-cli-clippy]
command = "cargo"
args = ["clippy", "--all-targets", "--all-features", "--", "-D", "warnings"]

[tasks.lint-check-cli]
dependencies = ["lint-check-cli-fmt", "lint-check-cli-clippy"]

[tasks.lint-fix-cli-fmt]
command = "cargo"
args = ["fmt"]

[tasks.lint-fix-cli-clippy]
command = "cargo"
args = [
    "clippy",
    "--all-targets",
    "--all-features",
    "--fix",
    "--allow-staged",
    "--",
    "-D",
    "warnings",
]

[tasks.lint-fix-cli]
dependencies = ["lint-fix-cli-fmt", "lint-fix-cli-clippy"]

[tasks.lint-check-ui]
command = "turbo"
args = ["lint"]

[tasks.lint-fix-ui]
command = "turbo"
args = ["lint:fix"]

[tasks.lint-check-style]
command = "pnpm"
args = ["run", "lint"]

[tasks.lint-fix-style]
command = "pnpm"
args = ["run", "lint:fix"]

[tasks.lint-check]
dependencies = ["lint-check-cli", "lint-check-ui", "lint-check-style"]

[tasks.lint-fix]
dependencies = ["lint-fix-cli", "lint-fix-ui", "lint-fix-style"]

[tasks.serve-service]
command = "cargo"
args = ["watch", "-x", "run -p plazer_service", "-w", "crates"]

[tasks.serve-cli]
command = "cargo"
args = ["watch", "-x", "run -p plazer", "-w", "crates"]

[tasks.serve-ui]
command = "pnpm"
args = ["run", "--filter", "{packages/ui}", "dev"]

[tasks.codegen-schema]
command = "cargo"
args = ["run", "-p", "plazer", "--", "schema", "--output", "schema.gql"]

[tasks.codegen-typeshare]
command = "typeshare"
args = [
    "--lang",
    "typescript",
    "--output-file",
    "packages/ui/src/__generated__/backend.d.ts",
    "crates/service",
]
install_crate = { crate_name = "typeshare-cli", binary = "typeshare", test_arg = "--version" }

[tasks.codegen-scss]
command = "turbo"
args = ["codegen:scss"]

[tasks.codegen-scss-watch]
command = "turbo"
args = ["codegen:scss:watch"]

[tasks.codegen-gql]
command = "turbo"
args = ["codegen:gql"]
dependencies = ["codegen-schema"]

[tasks.codegen-gql-watch]
command = "turbo"
args = ["codegen:gql:watch"]

[tasks.codegen]
dependencies = ["codegen-scss", "codegen-gql", "codegen-typeshare"]

[tasks.surreal-db]
command = "surreal"
args = ["start", "file://./data/db", "--pass", "root"]

[tasks.surreal-sql]
command = "surreal"
args = ["sql", "--conn", "ws://localhost:8000"]

[tasks.reset-local-db]
command = "rm"
args = ["-rf", "data/db"]

[config]
default_to_workspace = false

[env]
LLVM_PROFILE_FILE = '${CARGO_MAKE_WORKSPACE_WORKING_DIRECTORY}/target/coverage/raw/cargo-test-%p-%m.profraw'
