[package]
name = "c11ity"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = { version = "0.5.17", features = ["ws"] }
c11ity_client = { version = "0.1.0", path = "../client" }
c11ity_common = { version = "0.1.0", path = "../common", features = ["server"] }
tokio = { version = "1.22.0", features = ["full"] }
