[package]
name = "c11ity"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1.58"
axum = { version = "0.5.17", features = ["ws"] }
bincode = "1.3.3"
c11ity_client = { version = "0.1.0", path = "../client" }
c11ity_common = { version = "0.1.0", path = "../common", features = ["server"] }
serde = "1.0.147"
surrealdb = { version = "1.0.0-beta.8", features = ["kv-tikv"] }
tokio = { version = "1.22.0", features = ["full"] }
tracing = "0.1.37"
