[package]
name = "c11ity"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.70"
c11ity_service = { version = "0.1.0", path = "../service", features = [
    "schema-gen",
] }
clap = { version = "4.2.1", features = ["cargo", "derive"] }
tokio = { version = "1.22.0", features = ["macros", "rt-multi-thread"] }
