[package]
name = "c11ity_common"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
derive_more = "0.99.17"
serde = "1.0.147"
serde_with = "2.0.1"

[features]
server = []
client = []
