[package]
name = "c11ity_service"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.70"
async-graphql = { version = "5.0.7", features = [
    "chrono",
    "secrecy",
], default-features = false }
async-graphql-axum = "5.0.7"
async-stream = "0.3.5"
async-trait = "0.1.58"
axum = { version = "0.6.12", features = ["headers", "ws"] }
base64 = "0.21.0"
cfg-if = "1.0.0"
chrono = "0.4.24"
futures = "0.3.28"
hyper = "0.14.25"
jsonwebtoken = "8.3.0"
log = "0.4.17"
pkcs8 = { version = "0.10.2", features = ["alloc", "pem"] }
ring = { version = "0.16.20", features = ["alloc"], default-features = false }
secrecy = { version = "0.8.0", features = ["serde"] }
serde = "1.0.147"
serde_json = "1.0.89"
surrealdb = { version = "1.0.0-beta.9", features = [
    "kv-mem",
    "kv-rocksdb",
    "kv-tikv",
] }
thiserror = "1.0.40"
tokio = { version = "1.22.0", features = ["macros", "rt-multi-thread"] }
tracing = "0.1.37"
tracing-appender = "0.2.2"
tracing-subscriber = { version = "0.3.16", features = ["json"] }

[features]
graphiql = ["async-graphql/graphiql"]
