[package]
name = "c11ity_service"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-stream = "0.3.5"
axum = { version = "0.6.12", features = ["ws"] }
async-trait = "0.1.58"
async-graphql = "5.0.7"
c11ity_common = { version = "0.1.0", path = "../common", features = ["server"] }
futures = "0.3.28"
log = "0.4.17"
serde = "1.0.147"
serde_json = "1.0.89"
surrealdb = { version = "1.0.0-beta.9", features = ["kv-tikv"] }
tokio = { version = "1.22.0", features = ["macros", "rt-multi-thread"] }
tracing = "0.1.37"
tracing-subscriber = "0.3.16"
async-graphql-axum = "5.0.7"
