schema: "../../schema.gql"
documents: "src/**/*.{js,ts,jsx,tsx}"
exclude:
  - "src/**/__generated__/**"
config:
  enumsAsTypes: true
  immutableTypes: true
  nonOptionalTypename: true
  scalars:
    DateTime: "string"
  strictScalars: true
  useTypeImports: true
generates:
  ./src/__generated__/graphql.d.ts:
    plugins:
      - typescript
      - typescript-operations
