schema: "../../schema.gql"
documents: "src/**/*.{js,ts,jsx,tsx}"
exclude:
  - "src/**/__generated__/**"
config:
  preResolveTypes: true
  namingConvention: keep
  avoidOptionals:
    field: true
  nonOptionalTypename: true
  skipTypeNameForRoot: true
generates:
  ./src/__generated__/graphql.d.ts:
    plugins:
      - typescript
      - typescript-operations
