schema: "../../schema.gql"
documents: "src/**/*.{js,ts,jsx,tsx}"
exclude:
  - "src/**/*.gql.ts"
  - "src/**/__generated__/**"
config:
  preResolveTypes: true
  namingConvention: keep
  avoidOptionals:
    field: true
  nonOptionalTypename: true
  skipTypeNameForRoot: true
generates:
  ./src/__generated__/globalTypes.ts:
    plugins:
      - typescript
  ./src/__generated__:
    preset: near-operation-file
    presetConfig:
      extension: ".gql.ts"
      baseTypesPath: "./globalTypes.ts"
    plugins:
      - typescript-operations
